### PR TITLE
expose Hls.js global to allow plugin interaction

### PR DESCRIPTION
**Pull request by mrbar42**
### Description of the Changes

Some Hlsjs plugins rely on the existence of the `Hls` global.
exposing it will allow extending playkit-js-hls rather than writing another hls implementation.

### CheckLists

- [x] changes have been done against master branch, and PR does not conflict
- [x] new unit / functional tests have been added (whenever applicable)
- [x] test are passing in local environment 
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

### CODE REVIEW

**Comment by OrenMe** [comment]
thanks @shacharz, @mrbar42 - I would rather not expose hlsjs like this, and enable accessing it as es6 module or at least expose it on the namespace, but not overload it on the window.
We are exposing the config object though and allowing to pass it as is to the hls instance, will this do?

**Comment by mrbar42** [comment]
@OrenMe thanks for the response
by exposing on the namespace you mean something like `playkit.Hls`?
that will work for us.

as for passing options, we are not the ones that create the player instance so it might be difficult to pass options in

**Comment by OrenMe** [comment]
Hi @mrbar42 as we haven't yet planned to expose this we can mitigate the issue in the meanwhile and expose hls.js as `KalturaPlayer.hlsjs` but pay attention that this will change in the near future as we are transitioning our build system to support bundling module dependencies so you can just import the hls.js plugin.
Let me know if this interim solution as well as supporting the long term solution works out for you.

**Comment by mrbar42** [comment]
Hi @OrenMe, adding a reference of `Hls` on `KalturaPlayer` should do the trick for the near term.
The plugin based solution should work for us as well as we had a plugin for v2 which worked great.

Thanks for the assistance.

**Pull request closed without merging**
